### ISSUE TITLE
Can't run dockerfile

### ISSUE THREAD

**Issue by 9oelM** [lambdaclass/stark_compass_explorer#322]
I'm trying to launch the explorer locally with postgresql and then run it with [katana](https://github.com/dojoengine/dojo/tree/d4f36a226515d4ea6c75a7614db584f33f075e56/crates/katana)  for local RPC connection. To do that, I need to dockerize this repository. The existing dockerfile fails building after running this command:

```
git clone https://github.com/lambdaclass/stark_compass_explorer.git explorer-test 

cd explorer-test

docker build . -t explorer
```

<img width="1782" alt="image" src="https://github.com/lambdaclass/stark_compass_explorer/assets/22465806/b3e6ff12-6596-4e0a-a390-8375a120b554">

So I have to modify the file as:

```dockerfile
FROM hexpm/elixir:1.15.4-erlang-24.3.4.13-debian-bullseye-20230612 AS builder

ENV MIX_ENV=prod

WORKDIR /explorer
COPY . .

# @@@@@@@@@@@@@@@@@@@@@@@@@@@
# install git here
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git
# @@@@@@@@@@@@@@@@@@@@@@@@@@@
RUN mix local.hex --force
RUN mix local.rebar --force
RUN mix deps.get 
RUN mix assets.deploy
RUN mix phx.digest
RUN mix compile
RUN mix release
RUN mix phx.gen.release

FROM elixir:1.15.4-otp-24
ENV MIX_ENV=prod

WORKDIR /explorer

COPY --from=builder /explorer/_build/$MIX_ENV/rel/starknet_explorer .

EXPOSE 4000

CMD ["sh", "-c", "/explorer/bin/starknet_explorer eval 'StarknetExplorer.Release.migrate' && /explorer/bin/starknet_explorer start"]
```

And then it builds, but then it would fail to start when running `docker run` because migrating `priv/repo/migrations/20230929141348_change_blocks_pk.exs` fails probably due to https://github.com/lambdaclass/stark_compass_explorer/issues/309.

<img width="1330" alt="image" src="https://github.com/lambdaclass/stark_compass_explorer/assets/22465806/4220c7dd-6bf1-4c7a-a04e-9e035dd19f92">

But the thing is I'm not even using sqlite, but this error is about sqlite. 

My env vars are as follows:

```
RPC_API_HOST=http://katana:5050
TESTNET_RPC_API_HOST=http://katana:5050
TESTNET_2_RPC_API_HOST=http://katana:5050
DB_TYPE=postgresql
DATABASE_URL=ecto://user:supersecret@postgres:5432/dbname
SECRET_KEY_BASE=CSoyxe6b5xblTs9MJQnAochifCsJAsRduNystDUCkAsuSVIYE9heBsplWfkiJdkT
PHX_HOST=localhost
ENABLE_GATEWAY_DATA=true
ENABLE_MAINNET_SYNC=true
ENABLE_TESTNET_SYNC=false
ENABLE_TESTNET2_SYNC=false
```

what could be wrong?? I mean.. I got it working with the following Dockerfile eventually:

```dockerfile
FROM hexpm/elixir:1.15.4-erlang-24.3.4.13-debian-bullseye-20230612 AS builder

ENV MIX_ENV=prod

WORKDIR /explorer

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y git
RUN git clone https://github.com/lambdaclass/stark_compass_explorer.git . && \
    git reset --hard 4618aca68dbf0c037dbdfeac31603a9809592f24
    # this migration file causes an error when building the image due to
    # https://github.com/lambdaclass/stark_compass_explorer/issues/309
    # but we are starting from a fresh database so we can just remove it
    rm priv/repo/migrations/20230929141348_change_blocks_pk.exs
RUN mix local.hex --force
RUN mix local.rebar --force
RUN mix deps.get 
RUN mix assets.deploy
RUN mix phx.digest
RUN mix compile
RUN mix release
RUN mix phx.gen.release

FROM elixir:1.15.4-otp-24
ENV MIX_ENV=prod

WORKDIR /explorer

COPY --from=builder /explorer/_build/$MIX_ENV/rel/starknet_explorer .

EXPOSE 4000

CMD ["sh", "-c", "/explorer/bin/starknet_explorer eval 'StarknetExplorer.Release.migrate' && /explorer/bin/starknet_explorer start"]
```

Also, aside from this problem, do you guys expect RPC server to be v0.4.0? I'm running [katana](https://github.com/dojoengine/dojo/tree/d4f36a226515d4ea6c75a7614db584f33f075e56/crates/katana) and it only supports v0.3.0, and some things have been quite quirky, like some tabs not showing up properly or just crashing. Deleting the migration file supposedly shouldn't cause this problem because my local DB has nothing at the beginning anyway.

**Comment by Cevedale** [comment]
1)Build the Docker image:

docker build . -t explorer
This command builds the Docker image using the Dockerfile in the current directory and tags it with the name "explorer."

2)Run the Docker container:


docker run -p 80:80 explorer
